version: '3'
services:
  frontend:
    build: ./ResumeBuilderAngular
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./ResumeBuilderBackend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: